### PR TITLE
Fix empty stage occurrence

### PR DESCRIPTION
**Pull request by muizzk**

### CODE REVIEW

**Comment by paulkatsoulakis** [comment]
Hello, thanks for the PR.
Have you tested this and it indeed fixed the issue?
I did try that and didn't change anything, unless i had other issues at the same time and i didn't notice the side effect

**Comment by paulkatsoulakis** [comment]
woaaaa it does fix it! Weird, i did try removing the space but didn't fix it.

That makes things weird though, why it did it on the first two stages and not the others?

**Comment by muizzk** [comment]
Replying with an explanation on the ticket. Thanks

**Comment by paulkatsoulakis** [comment]
This is the time i tried and it was failing again: https://github.com/paulkatsoulakis/netdata/commit/ef15777c8a08a7b136bb97d7829ebd9c29c74361 

Thanks at any case, i 'll wait for the ticket feedback!

**Review by paulkatsoulakis — APPROVED** [review]

**Pull request merged**
